#!/bin/sh

# set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

cat /dev/null > /dev/tty 
if [ $? -ne 0 ]; then
    echo "true"
else
    echo "false"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
